apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-admin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-spring-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-spring-admin
    spec:
      containers:
        - name: sample-spring-admin
          image: piomin/sample-spring-admin
          ports:
            - containerPort: 8080
              name: http