apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-k8s
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-spring-k8s
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-spring-k8s
    spec:
      containers:
        - image: piomin/sample-spring-k8s
          name: sample-spring-k8s
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
#            - name: SPRING_CONFIG_IMPORT
#              value: "kubernetes:"

