kind: Secret
apiVersion: v1
metadata:
  name: sample-spring-k8s
  labels:
    spring.cloud.kubernetes.secret: "true"
data:
  application.properties: |-
    Y3VzdG9tLnNlY3VyZVByb3BlcnR5ID0gdGVzdA==
type: Opaque