spring:
  application.name: spring-kafka-consumer
  kafka:
    bootstrap-servers: my-kafka.kafka.svc.cluster.local:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

app.in.topic: ${TOPIC:info}