apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: caller-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "caller-service.ext"
#---
#apiVersion: networking.istio.io/v1beta1
#kind: DestinationRule
#metadata:
#  name: caller-service-destination
#spec:
#  host: caller-service
#  subsets:
#    - name: v1
#      labels:
#        version: v1
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: caller-service
spec:
  hosts:
    - "caller-service.ext"
  gateways:
    - caller-gateway
  http:
    - route:
        - destination:
            host: caller-service
#      timeout: 0.5s # - to enable if using Istio fault on callme-service route