version: 2.1

jobs:
  analyze:
    docker:
      - image: 'cimg/openjdk:25.0'
    steps:
      - git-shallow-clone/checkout_advanced:
          clone_options: '--filter=blob:none'
      - run:
          name: "Git fetch"
          command: git fetch --no-filter --refetch
      - run:
          name: Analyze on SonarCloud
          command: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests
  deploy-k8s:
    executor: vm
    steps:
      - checkout
      - run:
          name: Install OpenJDK 25
          command: |
            java -version
            sudo apt-get update && sudo apt-get install openjdk-25-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-25-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-25-openjdk-amd64/bin/javac
            java -version
            export JAVA_HOME=/usr/lib/jvm/java-25-openjdk-amd64
      - helm/install_helm_client
      - run:
          name: Install Kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Install Skaffold
          command: |
            curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
            chmod +x skaffold
            sudo mv skaffold /usr/local/bin
      - run:
          name: Install Kind
          command: |
            [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-amd64
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind
      - run:
          name: Create Kind Cluster
          command: |
            kind create cluster --name c1
      - run:
          name: Install Helm Charts
          command: |
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm repo add jetstack https://charts.jetstack.io
            helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
            helm install my-db bitnami/postgresql
            helm install cert-manager --namespace cert-manager --set crds.enabled=true --create-namespace jetstack/cert-manager
            helm install my-kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring --create-namespace
#      - run:
#          name: Docker Login
#          command: |
#            docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
#          env:
#            DOCKER_LOGIN: ${DOCKER_LOGIN}
#            DOCKER_PASSWORD: ${DOCKER_PASSWORD}
      - run:
          name: Deploy and Test
          command: |
            skaffold run --assume-yes=true --auto-create-config=false
            STATUS=$?
            if [ $STATUS -ne 0 ]; then
              mvn clean package -Pkubernetes -DskipTests
              mvn verify
            else
              mvn verify
              skaffold delete
            fi
      - run:
          name: Delete Kind Cluster
          command: |
            kind delete cluster --name c1

orbs:
  maven: circleci/maven@2.1.1
  helm: circleci/helm@3.2.0
  git-shallow-clone: guitarrapc/git-shallow-clone@2.8.0

executors:
  vm:
    machine:
      image: ubuntu-2204:current
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

workflows:
  build:
    jobs:
#      - maven/test:
#          command: 'test'
#          executor: vm
      - analyze:
          context: SonarCloud
      - deploy-k8s:
          context: Docker