apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-quarkus-k8s
data:
  application.properties: |
    simple.property = 123
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-quarkus-k8s
data:
  application.properties: |
    c2VjdXJlLnByb3BlcnR5ID0gMTIz
