apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-k8s
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-spring-k8s
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-spring-k8s
    spec:
      containers:
        - image: piomin/sample-spring-k8s
          name: sample-spring-k8s
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: /mnt/secrets-store/application.properties
          volumeMounts:
            - mountPath: /mnt/secrets-store
              name: secrets-store
              readOnly: true
            - mountPath: /config
              name: config-volume
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-database"
        - name: config-volume
          configMap:
            name: sample-spring-k8s