apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: callme-service
spec:
  host: callme-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
#  trafficPolicy: # --- enable for adding circuit breaker into DestinationRule
#    connectionPool:
#      http:
#        http1MaxPendingRequests: 1
#        maxRequestsPerConnection: 1
#        maxRetries: 0
#    outlierDetection:
#      consecutive5xxErrors: 3
#      interval: 30s
#      baseEjectionTime: 1m
#      maxEjectionPercent: 100
#---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: callme-service
spec:
  hosts:
    - callme-service
  http:
    - match:
        - headers:
            X-Version:
              exact: v1
      route:
        - destination:
            host: callme-service
            subset: v1
    - match:
        - headers:
            X-Version:
              exact: v2
      route:
        - destination:
            host: callme-service
            subset: v2
    - match:
        - withoutHeaders:
            X-Version: {}
      route:
        - destination:
            host: callme-service
            subset: v2
          weight: 80
        - destination:
            host: callme-service
            subset: v1
          weight: 20