apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-db-vault
spec:
  selector:
    matchLabels:
      app: sample-db-vault
  template:
    metadata:
      labels:
        app: sample-db-vault
    spec:
      containers:
      - name: sample-db-vault
        image: piomin/sample-db-vault
        ports:
        - containerPort: 8080
      serviceAccountName: spring-app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-db-vault
spec:
  type: ClusterIP
  selector:
    app: sample-db-vault
  ports:
  - port: 8080

