#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: sample-spring-k8s
#data:
#  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
#  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
#  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
#  CUSTOM_PROPERTY: "test"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-spring-k8s
data:
  application.properties: |
    management.endpoints.web.exposure.include = *
    management.endpoints.endpoint.health.show-details = always
    management.endpoints.endpoint.health.enabled = true
    custom.property = test
    server.port = 8443
    server.ssl.bundle = server
    spring.ssl.bundle.jks.server.keystore.location = ${CERT_PATH}/keystore.jks
    spring.ssl.bundle.jks.server.keystore.password = ${PASSWORD}
    spring.ssl.bundle.jks.server.keystore.type = JKS
    spring.ssl.bundle.jks.server.truststore.location = ${CERT_PATH}/truststore.jks
    spring.ssl.bundle.jks.server.truststore.password = ${PASSWORD}
    spring.ssl.bundle.jks.server.truststore.type = JKS
