apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-kafka
spec:
  selector:
    matchLabels:
      app: sample-spring-kafka
  template:
    metadata:
      labels:
        app: sample-spring-kafka
    spec:
      containers:
      - name: sample-spring-kafka
        image: piomin/sample-spring-kafka
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
        ports:
        - containerPort: 8080